# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Dmitry Novikov nerosketch@gmail.com, 2019.
#
#, fuzzy
msgid ""
msgstr ""
"Report-Msgid-Bugs-To: nerosketch@gmail.com\n"
"POT-Creation-Date: 2021-11-22 16:06+0300\n"
"Last-Translator: Dmitry Novikov nerosketch@gmail.com\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n"
"%100>=11 && n%100<=14)? 2 : 3);\n"

#: apps/devices/device_config/base.py:13
msgid "Device implementation error"
msgstr "Ошибка реализации устройства"

#: apps/devices/device_config/base.py:34
msgid "Device timeout error"
msgstr "Для устройства вышло время ожидания (Timeout)"

#: apps/devices/device_config/base_device_strategy.py:14
msgid "Hostname required for snmp"
msgstr "Адрес хоста необходим для snmp"

#: apps/devices/device_config/pon/epon/bdcom_p3310c.py:66
msgid "wait for a reply from the SNMP Timeout"
msgstr "Время ожидания ответа от SNMP истекло"

#: apps/devices/device_config/pon/epon/epon_bdcom_expect.py:31
#: apps/devices/device_config/pon/gpon/zte_utils.py:20
msgid "Wrong login or password for telnet access"
msgstr "Не правильный логин или пароль для доступа по telnet"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:37
#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:36
msgid "Ip address or parent device with ip address required for ONU device"
msgstr ""
"Необходим ip адрес. Или родительское устройство с назначенным ip адресом "
"необходимо."

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:40
msgid "For fetch additional device info, snmp community required"
msgstr ""
"Для получения дополнительной информации по устройству требуются snmp данные"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:77
#: apps/devices/device_config/pon/gpon/onu_zte_f660.py:87
msgid "name"
msgstr "имя"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:79
msgid "mtu"
msgstr ""

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:81
msgid "in_octets"
msgstr "входящий трафик"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:83
msgid "in_ucst_pkts"
msgstr "входящие unicast пакеты"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:85
msgid "in_not_ucst_pkts"
msgstr "входящие не unicast пакеты"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:87
msgid "in_discards"
msgstr "входящие отброшенные пакеты"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:89
msgid "in_errors"
msgstr "входящие ошибки"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:91
msgid "out_octets"
msgstr "исходящий трафик"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:93
msgid "out_ucst_pkts"
msgstr "исходящие unicast пакеты"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:95
msgid "out_not_ucst_pkts"
msgstr "исходящие не unicast пакеты"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:97
msgid "out_discards"
msgstr "исходящие отброшенные пакеты"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:99
msgid "out_errors"
msgstr "исходящие ошибки"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:100
msgid "uptime"
msgstr "Время в сети"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:104
msgid "ONU not connected"
msgstr "ONU не в сети"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:112
msgid "Onu snmp field must be en integer"
msgstr "Поле для snmp информации об ONU должно быть числом"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:158
#, python-format
msgid "Onu with mac \"%(onu_mac)s\" not found on OLT"
msgstr "Onu с мак адресом \"%(onu_mac)s\" не найдено на OLT"

#: apps/devices/device_config/pon/epon/epon_bdcom_fora.py:159
msgid "Parent device not found"
msgstr "Вышестоящее устройство не найдено"

#: apps/devices/device_config/pon/gpon/onu_config/zte_f601_static.py:35
#: apps/devices/device_config/pon/gpon/onu_config/zte_f660_dynamic_bridge_config.py:48
#: apps/devices/device_config/pon/gpon/onu_config/zte_f660_static_bridge_config.py:47
msgid "Multiple native vid is not allowed on one port"
msgstr "Несколько untagged vid не может быть на одном порту"

#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:39
msgid "Devices has not mac address."
msgstr "Устройство не имеет mac адреса в настройках."

#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:69
#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:184
#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:190
#, python-format
msgid "unregistered onu not found, sn=%s"
msgstr "Незарегистрированная onu с серийным номером '%s' не найдена"

#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:75
msgid "Success"
msgstr "Успешно"

#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:82
#: apps/devices/models.py:184
msgid "You should config parent OLT device for ONU"
msgstr "Вы должны указать родительское устройство OLT для ONU"

#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:84
#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:88
#: apps/devices/device_config/switch/dlink/dgs_1100_10me.py:40
#: apps/devices/models.py:186
msgid "You have not info in extra_data field, please fill it in JSON"
msgstr ""
"Не заполнено поле 'Техническая информация', обратитесь к администратору"

#: apps/devices/device_config/pon/gpon/onu_config/zte_onu.py:205
#, python-format
msgid "olt fiber %d is full"
msgstr "OLT глаз № %d заполнен"

#: apps/devices/device_config/pon/gpon/onu_zte_f660.py:90
msgid "vlans"
msgstr "вланы"

#: apps/devices/device_config/pon/gpon/onu_zte_f660.py:91
msgid "serial"
msgstr "серийник"

#: apps/devices/device_config/pon/gpon/onu_zte_f660.py:92
msgid "onu_type"
msgstr "тип onu"

#: apps/devices/device_config/pon/gpon/onu_zte_f660.py:200
msgid "Mac of device not equal mac by snmp"
msgstr "Мак устройства не совпадает с маком, полученным по snmp"

#: apps/devices/device_config/pon/gpon/onu_zte_f660.py:208
msgid "Could not fetch serial for onu"
msgstr "Не получается получить серийный номер для onu"

#: apps/devices/device_config/pon/gpon/zte_utils.py:39
msgid "Zte onu snmp field must be two dot separated integers"
msgstr ""
"Поле snmp информации для ZTE ONU должно быть двумя целыми числами, "
"разделенными точкой"

#: apps/devices/device_config/switch/dlink/dgs_1100_10me.py:24
#, python-format
msgid "File %(filename)s is not exists or not executable"
msgstr "Файл '%(filename)s' не существует или не исполняем"

#: apps/devices/device_config/switch/eltex/general.py:23
msgid "Eltex switch"
msgstr "Элтекс свич"

#: apps/devices/device_config/switch/eltex/mes5324a.py:11
msgid "Eltex MES5324A switch"
msgstr "Элтекс MES5324A свич"

#: apps/devices/device_config/switch/huawei/s2300.py:12
msgid "Huawei switch"
msgstr "Huawei свич"

#: apps/devices/device_config/switch/huawei/s2300.py:108
msgid "Huawei switch S5300"
msgstr "Huawei свич S5300"

#: apps/devices/device_config/switch/switch_device_strategy.py:141
msgid "Reboot not ready"
msgstr "Перезагрузка для устройства не готова"

#: apps/devices/models.py:58
msgid "Ip address"
msgstr "Ip адрес"

#: apps/devices/models.py:59
msgid "Mac address"
msgstr "Мак адрес"

#: apps/devices/models.py:60
msgid "Comment"
msgstr "Комментарий"

#: apps/devices/models.py:62
msgid "Device type"
msgstr "Тип устройства"

#: apps/devices/models.py:64
msgid "SNMP password"
msgstr "Пароль SNMP"

#: apps/devices/models.py:65
msgid "Device group"
msgstr "Группа устройства"

#: apps/devices/models.py:67
msgid "Parent device"
msgstr "Родительское устройство"

#: apps/devices/models.py:69
msgid "SNMP extra info"
msgstr "Доп. инфо для snmp"

#: apps/devices/models.py:71
msgid "Extra data"
msgstr "Дополнительные данные"

#: apps/devices/models.py:72
msgid "Extra data in JSON format. You may use it for your custom data"
msgstr ""
"Дополнительные данные в формате JSON. Вы можете хранить там собственные "
"данные"

#: apps/devices/models.py:76
msgid "Available vlans"
msgstr "Доступные vlan'ы"

#: apps/devices/models.py:83
msgid "Undefined"
msgstr "Не определено"

#: apps/devices/models.py:84
msgid "Up"
msgstr "В сети"

#: apps/devices/models.py:85
msgid "Unreachable"
msgstr "Не доступно"

#: apps/devices/models.py:86
msgid "Down"
msgstr "Не в сети"

#: apps/devices/models.py:88
msgid "Status"
msgstr "Состояние"

#: apps/devices/models.py:90
msgid "Send notify when monitoring state changed"
msgstr "Отправлять уведомления при событиях мониторинга"

#: apps/devices/models.py:93
msgid "Code"
msgstr "Код"

#: apps/devices/models.py:98 apps/devices/models.py:302
msgid "Create time"
msgstr ""

#: apps/devices/models.py:108
msgid "Device place address"
msgstr "Адрес установки устройства"

#: apps/devices/models.py:121 apps/devices/models.py:292
msgid "Device"
msgstr "Устройство"

#: apps/devices/models.py:122
msgid "Devices"
msgstr "Устройства"

#: apps/devices/models.py:124
msgid "Can remove from OLT"
msgstr "Может удалять с OLT"

#: apps/devices/models.py:125
msgid "Can fix onu"
msgstr "Может исправлять onu"

#: apps/devices/models.py:126
msgid "Can apply onu config"
msgstr "Может применять конфиг к onu"

#: apps/devices/models.py:199
msgid "Fixed"
msgstr "Исправлено"

#: apps/devices/models.py:268 apps/devices/models.py:284
msgid "Not chosen"
msgstr "Не выбрано"

#: apps/devices/models.py:269
msgid "Default"
msgstr "По умолчанию"

#: apps/devices/models.py:270
msgid "Untagged"
msgstr "Не тегирован"

#: apps/devices/models.py:271
msgid "Tagged"
msgstr "Тегирован"

#: apps/devices/models.py:272 apps/devices/models.py:287
msgid "Hybrid"
msgstr "Гибрид"

#: apps/devices/models.py:279 apps/devices/models.py:296
msgid "Operating mode"
msgstr "Режим"

#: apps/devices/models.py:285
msgid "Access"
msgstr "Доступ"

#: apps/devices/models.py:286
msgid "Trunk"
msgstr "Транк"

#: apps/devices/models.py:288
msgid "General"
msgstr ""

#: apps/devices/models.py:293
msgid "Number"
msgstr "Номер"

#: apps/devices/models.py:294
msgid "Description"
msgstr "Описание"

#: apps/devices/models.py:299
msgid "VLan list"
msgstr "Список VLAN'ов"

#: apps/devices/models.py:320
msgid "Can toggle ports"
msgstr "Может переключать порты"

#: apps/devices/models.py:322
msgid "Port"
msgstr "Порт"

#: apps/devices/models.py:323
msgid "Ports"
msgstr "Порты"

#: apps/devices/serializers.py:74
msgid "Config code"
msgstr "Код конфига"

#: apps/devices/views.py:175
msgid "Process locked by another process"
msgstr "Процесс занят другой задачей, подождите чуть и попробуйте ещё"

#: apps/devices/views.py:232
msgid "Deleted"
msgstr "Удалено"

#: apps/devices/views.py:233
msgid "Failed"
msgstr "Не получилось"

#: apps/devices/views.py:311
msgid "Device port count error"
msgstr "Ошибка подсчёта количества портов"

#: apps/devices/views.py:460
msgid "Parameter port_state is bad"
msgstr "Параметр port_state плох"

#~ msgid "Ip address required"
#~ msgstr "Ip адрес необходим"

#~ msgid "Subscribers on port does not exist"
#~ msgstr "Абоненты на порту не найдены"

#~ msgid "Device %(device_name)s is up"
#~ msgstr "Устройство %(device_name)s в сети"

#~ msgid "Device %(device_name)s is ok"
#~ msgstr "Устройство %(device_name)s всё ок"

#, python-format
#~ msgid "Device %(device_name)s is unreachable"
#~ msgstr "Устройство %(device_name)s не доступно"

#~ msgid "Device %(device_name)s has problem"
#~ msgstr "На '%(device_name)s' есть проблема"

#~ msgid "Device %(device_name)s getting undefined status code"
#~ msgstr "Устройство %(device_name)s имеет не известный код состояния"

msgid "Notify about device events"
msgstr "Оповещать о событиях устройств"
